export class RouteUrls {
  static readonly LOGIN: string = 'pages/Login';
  static readonly REGISTER: string = 'pages/RegisterPage';
  static readonly HOME: string = 'pages/HomePage';
  static readonly INDEX: string = 'pages/Index';
  static readonly EXAM_ADD: string = 'pages/ExamAddPage';
  static readonly EXAM_DETAIL: string = 'pages/ExamDetailPage';
  static readonly TASK_PREP: string = 'pages/PrepPage';
  static readonly RESOURCE_LIST: string = 'pages/ResourceListPage';
  static readonly RESOURCE_DETAIL: string = 'pages/ResourceDetailPage';
  static readonly TASK_ADD: string = 'pages/TaskAddPage';
  static readonly TASK_DETAIL: string = 'pages/TaskDetailPage';
  static readonly NOTIFICATION: string = 'pages/NotificationPage';
}
